spring:
  datasource:
    url: jdbc:mysql://localhost:33060/rentDB?createDatabaseIfNotExist=true
    username: root
    password: Ml22099478
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
  logging:
    level:
      org:
        hibernate:
          type: trace
  application:
    name: profile
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
server:
  port: 8181